<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Usuario</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/sistema/guardar-editar-usuario?idusuario=<?php echo $this->idusuario; ?>" data-callback="respuesta(response, 'Usuario actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Imagen</label>
            <div class="contenedor-imagen">
                <div style="background-image: url('<?php echo $this->img_user_perfil?>');" class="imagen"></div>
                <div class="btn btn-dark btn-sm waves-effect waves-themed" id="btn_cambiar_img_perfil"><i class="fas fa-upload"></i> Cambiar Imagen</div>
                <input type="file" id="img_perfil" onchange="cambiarImagen();" class="hidden" name="img_perfil" accept=".jpg,.jpeg,.png" style="display: none;">
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Correo Electrónico</label>
            <span>
                <input type="text" name="correo_electronico" class="form-control" value="<?php echo $this->email; ?>" readonly>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Nombres</label>
            <span>
                <input type="text" name="nombres" class="form-control" value="<?php echo $this->nombres; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Paterno</label>
            <span>
                <input type="text" name="apellido_paterno" class="form-control" value="<?php echo $this->apellido_paterno; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Materno</label>
            <span>
                <input type="text" name="apellido_materno" class="form-control" value="<?php echo $this->apellido_materno; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Teléfono</label>
            <span>
                <input type="text" name="telefono" class="form-control" value="<?php echo $this->telefono; ?>">
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-users"></i>&nbsp;Perfil de Usuario</h2>
        </div>
        <div class="form-group">
            <label class="form-label">Perfil</label>
            <span>
                <select class="select2 form-control" name="idperfil">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->perfiles as $perfiles):?>
                    <option value="<?php echo $perfiles['idperfil'];?>" <?php if( $this->idperfil == $perfiles['idperfil'] ) echo "selected='select'"; ?>><?php echo $perfiles['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <?php if( $this->idusuario != 1) : ?>
        <span id="seccion-feria">
            <div class="panel-hdr">
                <h2><i class="fas fa-fw fa-lg fa-home"></i>&nbsp;Feria</h2>
            </div>
            <div class="form-group">
                <label class="form-label">Feria</label>
                <span>
                    <select class="select2 form-control" name="idferias">
                        <option value="" selected="select" disabled="">Seleccionar...</option>
                        <?php foreach($this->ferias as $ferias):?>
                        <option value="<?php echo $ferias['idferias'];?>" <?php if( $this->idferias == $ferias['idferias'] ) echo "selected='select'"; ?>><?php echo $ferias['nombre'];?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </span>
        <?php endif; ?>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-key"></i>&nbsp;Cambiar Contraseña</h2>
        </div>
        <div class="form-group">
            <label class="form-label">Contraseña</label>
            <span>
                <input type="password" name="contrasena" id="contrasena" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Repita Contraseña</label>
            <span>
                <input type="password" name="repita_contrasena" class="form-control">
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#btn_cambiar_img_perfil").click(function () {
        $("#img_perfil").click();
    });

    $("select[name='idperfil']").change(function(){
        if( $(this).val() == '1' )$("#seccion-feria").hide();
        else $("#seccion-feria").show();
    });

    function cambiarImagen() {
        var file = document.getElementById('img_perfil').files[0];
        var reader = new FileReader();
        reader.onload = function (e) {
            $('.contenedor-imagen .imagen').css({'background-image':'url('+e.target.result+')'});
        };
        reader.readAsDataURL(file);
    }

    $("#validar_formulario").validate({
        rules: {
            nombres: {
                required: true
            },
            correo_electronico: {
                required: true,
                email: true
            },
            apellido_paterno: {
                required: true
            },
            contrasena: {
                required: false,
                minlength: 6,
                maxlength: 20
            },
            repita_contrasena: {
                required: false,
                minlength: 6,
                maxlength: 20,
                equalTo: '#contrasena'
            },
            idperfil: {
                required: true
            },
            usuario: {
                required: true
            },
            <?php if( $this->idusuario != 1) : ?>
            idferias: {
                required: true
            }
            <?php endif; ?>
        },
        messages: {
            nombres: {
                required: 'Por favor, ingrese los nombres'
            },
            correo_electronico: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            },
            apellido_paterno: {
                required: 'Por favor, ingrese el apellido paterno'
            },
            contrasena: {
                required: 'Por favor, ingrese la contraseña',
                minlength: 'Por favor, introduzca al menos 6 caracteres',
                maxlength: 'Por favor, introduzca no más de 20 caracteres'
            },
            repita_contrasena: {
                required: 'Por favor, ingrese la contraseña una vez más',
                equalTo: 'Por favor, ingrese la misma contraseña que el anterior',
                minlength: 'Por favor, introduzca al menos 6 caracteres',
                maxlength: 'Por favor, introduzca no más de 20 caracteres'
            },
            idperfil: {
                required: 'Por favor, seleccione el perfil'
            },
            usuario: {
                required: 'Por favor, ingrese el usuario'
            },
            <?php if( $this->idusuario != 1) : ?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            }
            <?php endif; ?>
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>