<style>
    .contenedor-dinamico .contenido .form-group{
        border-bottom: 3px solid rgba(0, 0, 0, 0.07);
    }    
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Banner</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-agregar-banner" data-callback="respuesta(response, 'Banner agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Categoria</label>
            <span>
                <select class="select2 form-control select-categoria" name="categoria">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->categoriasBanner as $item):?>
                    <option value="<?php echo $item;?>"><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-clock"></i>&nbsp;Programar Fechas</h2>
        </div>
        <div class="contenedor-dinamico lista-submodulos">
            <input type="hidden" name="submodulos">
            <div class="encabezado">
                <div class="row">
                    <div class="col-md-12"></div>
                </div>
            </div>
            <div class="plantilla" style="display: none;">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label">Proyecto</label>
                                <span>
                                    <select class="select2 form-control" name="idproductos[]">
                                        <option value="" selected="select" disabled="">Seleccionar...</option>
                                        <?php foreach($this->proyectos as $item):?>
                                        <option value="<?php echo $item['idproductos'];?>"><?php echo $item['nombre']." (".$item['segmento'].")"; ?></option>
                                        <?php endforeach;?>
                                    </select>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label">Banner</label>
                                <div class="contenedor-imagen-personalizado">
                                    <img src="<?php echo ( $this->hash_fondo_principal != '' ) ? 'portal/imagenes/'.$this->hash_fondo_principal : 'plantillas/imagenes/banner-inicial.jpg'; ?>" width="1725" class="imagen" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 1725 px de ancho y 284 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="1725" data-height="284" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_fondo_principal" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                    <div class="row mt-10">
                                        <div class="col-md-12">
                                            <label class="form-label">Programar Rango de Fechas</label>
                                            <div class="input-daterange input-group calendario">
                                                <input type="text" class="form-control" name="fondo_principal_prog_fecha_inicio" value="<?php echo ( $this->fondo_principal_prog_fecha_inicio != '' ) ? date('d/m/Y', strtotime($this->fondo_principal_prog_fecha_inicio)) : date('d/m/Y'); ?>">
                                                <div class="input-group-append input-group-prepend">
                                                    <span class="input-group-text fs-xl"><i class="fal fa-ellipsis-h"></i></span>
                                                </div>
                                                <input type="text" class="form-control" name="fondo_principal_prog_fecha_fin" value="<?php echo ( $this->fondo_principal_prog_fecha_fin != '' ) ? date('d/m/Y', strtotime($this->fondo_principal_prog_fecha_fin)) : date('d/m/Y'); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <span class="icon-delete" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="contenido"></div>
            <div class="opcion">
                <button type="button" class="btn btn-success btn-block" onclick="Fila.agregar(this)"><i class="fas fa-plus"></i> Agregar Banner</button>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Banner</button>
    </div>
</form>

<script>

    $(".select-categoria").select2();

    $(document).on("click", ".cambiar-imagen-personalizado", function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        var dataImagenInicial = $(obj).attr("data-imagen-inicial");
        dataImagenInicial = (dataImagenInicial !== undefined ) ? dataImagenInicial : 'plantillas/imagenes/banner-inicial.jpg';
        console.log(dataImagenInicial);
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", dataImagenInicial);
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    var Fila = {
        agregar: function(obj){
            let idInputIcono = $.now();
            let contenedor = $(obj).parents(".contenedor-dinamico");
            let plantilla = contenedor.find(".plantilla");
            let plantillaContenido = $("<div>").html(plantilla.html());
            let contenido = contenedor.find(".contenido");
            plantillaContenido.find(".contenedor-icono").attr({
                "data-idicono": idInputIcono,
                "onclick": "abrirModalIcono('"+idInputIcono+"')"
            });
            contenido.append(plantillaContenido.html());
            contenido.find(".select2").select2();
            initCalendario();
        },
        eliminar: function(obj){
            $(obj).parents(".form-group").remove();
            guardarSubmodulos();
        }
    }

    function initCalendario(){
        $(".calendario").datepicker({
            todayHighlight: true,
            templates: {
                leftArrow: '<i class="fal fa-angle-left" style="font-size: 1.25rem"></i>',
                rightArrow: '<i class="fal fa-angle-right" style="font-size: 1.25rem"></i>'
            },
            language: 'es',
            orientation: "top",
            autoclose: true
        });
    }

    $("#validar_formulario").validate({
        rules: {
            categoria: {
                required: true
            }
        },
        messages: {
            categoria: {
                required: 'Por favor, seleccione la categoria'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>