<style>
.label-info {
    background-color: #5bc0de;
}
.label {
    display: inline;
    padding: .2em .6em .3em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .25em;
}
.bootstrap-tagsinput{
    width: 100%;
    height: calc(1.47em + 1rem + 2px);
    border: 1px solid #E5E5E5;
    box-shadow: none;
}
</style>

<div class="modal-header">
    <h4 class="modal-title">Configurar Correos</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-configurar-correos-portal" data-callback="respuesta(response, 'Correo guardado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <input type="hidden" name="idportal" value="<?php echo $this->idportal; ?>">
        <div class="form-group">
            <label class="form-label">Plantilla</label>
            <span>
                <select class="select2 form-control" name="plantilla_correo">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->plantillaCorreos as $key => $item):?>
                    <option value="<?php echo $key;?>"><?php echo ucwords(mb_strtolower($item['value']));?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div data-config="correos" style="display:none;">
            <div class="form-group">
                <label class="form-label">Asunto</label>
                <span>
                    <input type="text" name="asunto" class="form-control">
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">CC</label>
                <span>
                    <select class="tagsselect" name="correo_copia[]" multiple data-role="tagsinput"></select>
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">Contenido</label>
                <span>
                    <textarea name="contenido" id="editor" class="form-control"></textarea>
                </span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Datos</button>
    </div>
</form>

<script>

    var contenidoCorreo = CKEDITOR.replace('editor');

    contenidoCorreo.on('change', function(evt) {
        $("textarea[name='contenido']").html(evt.editor.getData());
    });

    $("select[name='plantilla_correo']").change(function(){
        let plantilla = $(this).val();
        if(plantilla != '') {
            $("[data-config='correos']").show();
            $.post("/cliente/obtener-plantilla-correos", {idportal: '<?php echo $this->idportal; ?>', plantilla: plantilla}, function(data){
                if(Object.keys(data).length){
                    console.log("data", data);
                    $("input[name='asunto']").val(data.asunto);
                    CKEDITOR.instances.editor.setData(data.contenido);
                    if(data.correo_copia != ''){
                        let correos_copia = data.correo_copia.split(",");
                        if(correos_copia.length){
                            $("select[name='correo_copia[]']").html('');
                            correos_copia.forEach(function(item){
                                let option = $('<option>');
                                option.attr("value", item),
                                option.text(item);
                                $("select[name='correo_copia[]']").append(option);
                            });
                            tagsSelect('restart');
                        }
                    }
                } else {
                    tagsSelect('delete');
                    CKEDITOR.instances.editor.setData('');
                }
            }, 'json');
        }
    });

    function tagsSelect(accion){
        switch(accion){
            case 'delete':
                $(".tagsselect").html(''),
                $(".tagsselect").tagsinput('destroy');
                $(".tagsselect").tagsinput('items');
            break;
            case 'restart':
                $(".tagsselect").tagsinput('destroy');
                $(".tagsselect").tagsinput('items');
            break;
        }
    }

    $(".select2").select2();
    $(".tagsselect").tagsinput('items');

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            para: {
                required: true,
                email: true,
            },
            asunto: {
                required: true
            },
            correo_copia: {
                required: true
            }
        },
        messages: {
            para: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            },
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>