<style>
    .contenedor-tabs .tab-content{
        margin-top: 8px;
    }
    .modal-dialog .modal-body .form-group {
        margin-bottom: 0.6rem;
    }
    .grupo-colores{
        padding: 0 6px;
        border: 1px solid #ddd;
        border-radius: 10px;
        margin-bottom: 6px;
    }
    .grupo-colores .panel-hdr{
        margin-bottom: 6px !important;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Personalizar Portal</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-configurar-portal" data-callback="respuesta(response, 'Configuración guardado correctamente.')" autocomplete="off">
    <input type="hidden" name="idportal" value="<?php echo $this->idportal; ?>">
    <div class="modal-body">
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-2" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Imágenes</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-brush"></i> Personalizar Colores</a></li>
            </ul>
            <div class="tab-content">
                <!-- INICIO TAB -->
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Texto Título Formulario</label>
                        <span>
                            <input type="text" name="texto_titulo_formulario" class="form-control" value="<?php echo $this->texto_titulo_formulario; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">URL Video Tutorial</label>
                        <span>
                            <input type="text" name="url_video_tutorial" class="form-control" value="<?php echo $this->url_video_tutorial; ?>">
                        </span>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-2" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Logo</label>
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->hash_logo != '' ) ? 'portal/imagenes/'.$this->hash_logo : 'plantillas/imagenes/LOGO-EXPOHOGAR.svg'; ?>" width="270" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 270 px de ancho y 58 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="270" data-height="58" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_logo" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Logo Banner</label>
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->hash_logo_banner != '' ) ? 'portal/imagenes/'.$this->hash_logo_banner : 'plantillas/imagenes/lap-responsive.png'; ?>" width="500" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 500 px de ancho y 332 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="500" data-height="332" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_logo_banner" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Fondo Principal</label>
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->hash_fondo_principal != '' ) ? 'portal/imagenes/'.$this->hash_fondo_principal : 'plantillas/imagenes/feria-intro-register.jpg'; ?>" width="2000" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 2000 px de ancho y 1109 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="2000" data-height="1109" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_fondo_principal" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                            <div class="row mt-10">
                                <div class="col-md-12">
                                <label class="form-label">Programar Rango de Fechas</label>
                                    <div class="input-daterange input-group calendario">
                                        <input type="text" class="form-control" name="fondo_principal_prog_fecha_inicio" value="<?php echo ( $this->fondo_principal_prog_fecha_inicio != '' ) ? date('d/m/Y', strtotime($this->fondo_principal_prog_fecha_inicio)) : date('d/m/Y'); ?>">
                                        <div class="input-group-append input-group-prepend">
                                            <span class="input-group-text fs-xl"><i class="fal fa-ellipsis-h"></i></span>
                                        </div>
                                        <input type="text" class="form-control" name="fondo_principal_prog_fecha_fin" value="<?php echo ( $this->fondo_principal_prog_fecha_fin != '' ) ? date('d/m/Y', strtotime($this->fondo_principal_prog_fecha_fin)) : date('d/m/Y'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="panel-hdr">
                        <h2>Formulario Principal</h2>
                    </div>
                    <div class="grupo-colores">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Título</h2>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Color</label>
                                    <span>
                                        <input type="color" name="form_principal_titulo_color_texto" class="form-control" value="<?php echo $this->form_principal_titulo_color_texto; ?>">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="grupo-colores">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Campo</h2>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Fondo</label>
                                    <span>
                                        <input type="color" name="form_principal_campo_fondo_color" class="form-control" value="<?php echo $this->form_principal_campo_fondo_color; ?>">
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Texto</label>
                                    <span>
                                        <input type="color" name="form_principal_campo_color_texto" class="form-control" value="<?php echo $this->form_principal_campo_color_texto; ?>">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="grupo-colores">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Botón</h2>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Texto</label>
                                    <span>
                                        <input type="color" name="form_principal_boton_color_texto" class="form-control" value="<?php echo $this->form_principal_boton_color_texto; ?>">
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Fondo</label>
                                    <span>
                                        <input type="color" name="form_principal_boton_fondo_color" class="form-control" value="<?php echo $this->form_principal_boton_fondo_color; ?>">
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label">Hover</label>
                                    <span>
                                        <input type="color" name="form_principal_boton_hover_color" class="form-control" value="<?php echo $this->form_principal_boton_hover_color; ?>">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info btn-submit btn-uploader-form" data-id-form="validar_formulario">Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $(".calendario").datepicker({
        todayHighlight: true,
        templates: {
            leftArrow: '<i class="fal fa-angle-left" style="font-size: 1.25rem"></i>',
            rightArrow: '<i class="fal fa-angle-right" style="font-size: 1.25rem"></i>'
        },
        language: 'es',
        orientation: "top",
        autoclose: true
    });
     
    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        var dataImagenInicial = $(obj).attr("data-imagen-inicial");
        dataImagenInicial = (dataImagenInicial !== undefined ) ? dataImagenInicial : 'img/no-imagen.jpg';
        console.log(dataImagenInicial);
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", dataImagenInicial);
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    $("#validar_formulario").validate({
        rules: {
            config_terminos_condiciones:{
                required: false
            },
            config_buscador_titulo:{
                required: true
            },
        },
        messages: {},
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }/*,
        submitHandler: function(form) {
            guardarDatos($(form).serialize());
        }*/
    });


    function guardarDatos(data) {
        $.post("/cliente/guardar-configurar-ferias",data,function(response){
            if(response.result === 'success') {
                ocultarModal();
                alerta('Configuración guardado correctamente.', 'success');
            }
        }, 'json');
    }

</script>