<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Banner</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-editar-banner?idbanner=<?php echo $this->idbanner; ?>" data-callback="respuesta(response, 'Banner actualizado correctamente.')" autocomplete="off">
<div class="modal-body">
        <div class="form-group">
            <label class="form-label">Categoria</label>
            <span>
                <select class="select2 form-control select-categoria" name="categoria">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->categoriasBanner as $item):?>
                    <option value="<?php echo $item;?>" <?php if( $this->categoria == $item ) echo "selected='select'"; ?>><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="content-select-proyectos" style="display: none">
            <div class="form-group">
                <label class="form-label">Proyecto</label>
                <span>
                    <select class="select2 form-control" name="idproductos">
                        <option value="" selected="select" disabled="">Seleccionar...</option>
                        <?php foreach($this->proyectos as $item):?>
                        <option value="<?php echo $item['idproductos'];?>" <?php if( $this->categoria == 'PROYECTO' && $this->idtabla == $item['idproductos'] ) echo "selected='select'"; ?>><?php echo $item['nombre']." (".$item['segmento'].")"; ?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div class="content-select-bancos" style="display: none">
            <div class="form-group">
                <label class="form-label">Banco</label>
                <span>
                    <select class="select2 form-control" name="idbancos">
                        <option value="" selected="select" disabled="">Seleccionar...</option>
                        <?php foreach($this->bancos as $item):?>
                        <option value="<?php echo $item['idbancos'];?>" <?php if( $this->categoria == 'BANCO' && $this->idtabla == $item['idbancos'] ) echo "selected='select'"; ?>><?php echo $item['nombre']; ?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div class="content-select-empresas" style="display: none">
            <div class="form-group">
                <label class="form-label">Inmobiliaria</label>
                <span>
                    <select class="select2 form-control" name="idempresas">
                        <option value="" selected="select" disabled="">Seleccionar...</option>
                        <?php foreach($this->empresas as $item):?>
                        <option value="<?php echo $item['idempresas'];?>" <?php if( $this->categoria == 'INMOBILIARIA' && $this->idtabla == $item['idempresas'] ) echo "selected='select'"; ?>><?php echo $item['nombre']; ?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div class="content-select-pagina-posicion" style="display: none">
            <div class="form-group">
                <label class="form-label">Posición Banner</label>
                <span>
                    <select class="select2 form-control" name="idposicionbanner">
                        <option value="" selected="select">Seleccionar...</option>
                        <?php foreach($this->posiciones as $item):?>
                            <option value="<?php echo $item['idposicionbanner']; ?>" <?php if( $this->idposicionbanner == $item['idposicionbanner'] ) echo "selected='select'"; ?>><?php echo $item['pagina']." - ".$item['nombre']; ?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div class="contenido-banner" style="display: none">
            <div class="form-group">
                <label class="form-label">Banner</label>
                <div class="contenedor-imagen-personalizado">
                    <img src="<?php echo ( $this->hash_banner != '' ) ? 'banner/imagenes/'.$this->hash_banner : 'plantillas/imagenes/banner-inicial.jpg'; ?>" width="1725" class="imagen" alt="" style="max-height: 220px;">
                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5"><!-- Imagen recomendada de 1725 px de ancho y 284 px de alto --></div>
                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                    <input type="file" data-width="1725" data-height="284" onchange="cambiarImagenDimension(this, event);" class="hidden" name="imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                    <div class="row mt-10">
                        <div class="col-md-12">
                        <label class="form-label">Programar Rango de Fechas</label>
                            <div class="input-daterange input-group calendario">
                                <input type="text" class="form-control" name="fecha_programa_inicio" value="<?php echo ( $this->fecha_programa_inicio != '' ) ? date('d/m/Y', strtotime($this->fecha_programa_inicio)) : date('d/m/Y'); ?>" required>
                                <div class="input-group-append input-group-prepend">
                                    <span class="input-group-text fs-xl"><i class="fal fa-ellipsis-h"></i></span>
                                </div>
                                <input type="text" class="form-control" name="fecha_programa_fin" value="<?php echo ( $this->fecha_programa_fin != '' ) ? date('d/m/Y', strtotime($this->fecha_programa_fin)) : date('d/m/Y'); ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(document).ready(function() {
        $(".select-categoria").change();
    });

    $(".select-categoria").change(function(){
        $(".content-select-proyectos, .content-select-bancos, .content-select-empresas, .content-select-pagina-posicion, .contenido-banner").hide();
        $("select[name='idproductos'], select[name='idbancos']").rules( "add", { required: false });
        if($(this).val() === 'PROYECTO') {
            $(".content-select-proyectos").show();
            $("select[name='idproductos']").rules( "add", { required: true });
        } else if($(this).val() === 'INMOBILIARIA') {
            $(".content-select-empresas").show();
            $("select[name='idempresas']").rules( "add", { required: true });
        } else {
            $(".content-select-bancos").show();
            $("select[name='idbancos']").rules( "add", { required: true });
        }
        $(".content-select-pagina-posicion, .contenido-banner").show();
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        var dataImagenInicial = $(obj).attr("data-imagen-inicial");
        dataImagenInicial = (dataImagenInicial !== undefined ) ? dataImagenInicial : 'plantillas/imagenes/banner-inicial.jpg';
        console.log(dataImagenInicial);
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                /*if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", dataImagenInicial);
                    return false;
                }*/
                img.attr("src", e.target.result);
            };
        }
    }

    $(".calendario").datepicker({
        todayHighlight: true,
        templates: {
            leftArrow: '<i class="fal fa-angle-left" style="font-size: 1.25rem"></i>',
            rightArrow: '<i class="fal fa-angle-right" style="font-size: 1.25rem"></i>'
        },
        language: 'es',
        orientation: "top",
        autoclose: true
    });

    $(".select2").select2()

    $("#validar_formulario").validate({
        rules: {
            categoria: {
                required: true
            },
            idposicionbanner: {
                required: true
            }
        },
        messages: {
            categoria: {
                required: 'Por favor, seleccione la categoria'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>