<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Portal Banner</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-editar-portalbanner?idportalbanner=<?php echo $this->idportalbanner; ?>" data-callback="respuesta(response, 'PortalBanner actualizado correctamente.')" autocomplete="off">
    <input type="hidden" name="idportal" value="<?php echo $this->idportal; ?>">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Posición Banner</label>
            <span>
                <select class="select2 form-control" name="idposicionbanner">
                    <option value="" selected="select">Seleccionar...</option>
                    <?php foreach($this->posiciones as $item):?>
                        <option value="<?php echo $item['idposicionbanner']; ?>" <?php if( $this->idposicionbanner == $item['idposicionbanner'] ) echo "selected='select'"; ?>><?php echo $item['pagina']." - ".$item['nombre']; ?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Banner</label>
            <div class="contenedor-imagen-personalizado">
                <img src="<?php echo ( $this->hash_banner != '' ) ? 'portal/banner/'.$this->hash_banner : 'plantillas/imagenes/banner-inicial.jpg'; ?>" class="imagen" alt="" style="max-height: 320px;">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5"><!-- Imagen recomendada de 1725 px de ancho y 284 px de alto --></div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="1725" data-height="284" onchange="cambiarImagenDimension(this, event);" class="hidden" name="imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        var dataImagenInicial = $(obj).attr("data-imagen-inicial");
        dataImagenInicial = (dataImagenInicial !== undefined ) ? dataImagenInicial : 'img/no-imagen.jpg';
        console.log(dataImagenInicial);
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                /*if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", dataImagenInicial);
                    return false;
                }*/
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            idposicionbanner: {
                required: true
            }
        },
        messages: {},
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>