<style>
    .contenedor-tabs .tab-content{
        margin-top: 8px;
    }
    .lista-submodulos .contenido input[data-name="titulo"] {
        font-weight: 500;
    }
    .row-img {
        position: relative;
        padding: 4px 8px 8px;
        background-color: #c5c5c526;
        border-radius: 4px;
        margin-bottom: 6px;
    }
    .row-img:last-child{
        margin-bottom: 0px;
    }
    .row-img .bloque:first-child{
        margin-bottom: 4px;
    }
    .row-img i.remove{
        position: absolute;
        right: 8px;
        top: 3px;
        font-size: 16px;
        color: #a0a0a0;
        cursor: pointer;
    }
    .row-img .bg_imagen{
        width: 100%;
        height: 50px;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        border-radius: 4px;
        background-color: #ececec;
        position: relative;
        cursor: pointer;
    }
    .row-img .bg_imagen .icon{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        color: #ababab;
    }
    .row-img .bg_imagen .icon i{
        font-size: 26px;
        line-height: 1;
    }

    /*Maps*/
    #map {
	    height: 450px;
	}
	.controls {
        margin-top: 10px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
	}
	#inputSearch {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 300px;
	}
	#inputSearch:focus {
	    border-color: #4d90fe;
	}
	.pac-container {
        font-family: Roboto;
        z-index: 10000;
	}
	#type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
	}
	#type-selector label {
        font-family: Roboto;
        font-size: 13px;
	    font-weight: 300;
	}
	#target {
	    width: 345px;
	}
	.smart-form *, .smart-form :after, .smart-form :before {
	    box-sizing: inherit;
	    -moz-box-sizing: inherit;
	}
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Proyecto</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/producto/guardar-agregar-productos" data-callback="respuesta(response, 'Proyecto agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <!-- Parámetros Mapa -->
        <input type="hidden" name="latitud" id="latitud" readonly="" value="0">
		<input type="hidden" name="longitud" id="longitud" readonly="" value="0">
        <!-- TABS [INICIO] -->
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Detalle</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-2" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Imagenes</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-4" role="tab"><i class="fas fa-fw fa-lg fa-map-marked-alt"></i> Ubicación</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-5" role="tab"><i class="fas fa-fw fa-lg fa-video"></i> Video</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Empresa</label>
                        <span>
                            <select class="select2 form-control" name="idempresas">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->empresas as $item):?>
                                <option value="<?php echo $item['idempresas'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Nombre</label>
                        <span>
                            <input type="text" name="nombre" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Descripción</label>
                        <span>
                            <input type="text" name="descripcion" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Dirección</label>
                        <span>
                            <input type="text" name="direccion" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Tipo Enlace</label>
                        <span>
                            <select class="select2 form-control select-tipoenlace" name="tipo_enlace">
                                <option value="" selected="select">Seleccionar...</option>
                                <option value="URL">URL</option>
                                <option value="PDF">PDF</option>
                            </select>
                        </span>
                    </div>
                    <span data-contenedor="enlace" style="display: none;">
                        <div class="form-group">
                            <label class="form-label">Enlace</label>
                            <span>
                                <input type="text" name="enlace" class="form-control">
                            </span>
                        </div>
                    </span>
                    <span data-contenedor="pdf" style="display: none;">
                        <div class="form-group">
                            <label class="form-label">PDF</label>
                            <div class="contenedor-archivo">
                                <button type="button" class="btn btn-default btn-archivo">Seleccionar archivo</button>
                                <button type="button" class="btn btn-danger btn-eliminar" style="display: none;" onclick="File.delete(this)"><i class="fas fa-times"></i></button>
                                <a href="javascript:void(0)" download class="btn btn-primary btn-descargar" style="display: none;"><i class="fas fa-download"></i> Descargar</a>
                                <input type="file" name="archivo_pdf" class="form-control" size-valid="5000000" valid-file="application/pdf" onchange="File.upload(this, event);" accept="application/pdf" style="display: none;">
                                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">El peso máximo del archivo es de 5 MB</div>
                            </div>
                        </div>
                    </span>
                    <div class="form-group">
                        <label class="form-label">Enlace Whatsapp</label>
                        <span>
                            <input type="text" name="enlace_wsp" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Mapa</label>
                        <span>
                            <input type="text" name="enlace_mapa" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Recorrido Virtual</label>
                        <span>
                            <input type="text" name="enlace_recorrido_virtual" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Recorrido Virtual 360</label>
                        <span>
                            <input type="text" name="recorrido_virtual_360" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Distrito</label>
                        <span>
                            <select class="select2 form-control" name="iddistritos">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->distritos as $item):?>
                                <option value="<?php echo $item['iddistritos'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Tipo de Habitación</label>
                        <span>
                            <select class="select2 form-control" name="idtipohabitacion">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->tipoHabitaciones as $item):?>
                                <option value="<?php echo $item['idtipohabitacion'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Número de Habitación</label>
                        <span>
                            <select class="select2 form-control" name="idnumerohabitacion">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->numeroHabitaciones as $item):?>
                                <option value="<?php echo $item['idnumerohabitacion'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Etapa</label>
                        <span>
                            <select class="select2 form-control" name="idetapa">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->etapas as $item):?>
                                <option value="<?php echo $item['idetapa'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Título Recuadro</label>
                        <span>
                            <input type="text" name="titulo_recuadro" class="form-control">
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-check"></i>&nbsp;Destacado</h2>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox custom-control-inline mt-1">
                            <input type="checkbox" name="destacado" value="1" class="custom-control-input" id="defaultInline1">
                            <label class="custom-control-label" for="defaultInline1"><span class=""></span> Activar</label>
                        </div>
                    </div>
                    <div class="contenido-imagen-oferta" style="display: none">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen Super Oferta</h2>
                        </div>
                        <div class="form-group">   
                            <div class="contenedor-imagen-personalizado">
                                <img src="plantillas/imagenes/sale-absolut.png" width="134" class="imagen" alt="">
                                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 134 px de ancho y 101 px de alto</div>
                                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                <input type="file" data-width="134" data-height="101" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_super_oferta" accept=".jpg,.jpeg,.png" style="display: none;">
                                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-check"></i>&nbsp;Sala de Venta</h2>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox custom-control-inline mt-1">
                            <input type="checkbox" name="sala_venta" value="1" class="custom-control-input" id="defaultInline2">
                            <label class="custom-control-label" for="defaultInline2"><span class=""></span> Activar</label>
                        </div>
                    </div>
                    <div class="contenido-sala-venta" style="display: none;">
                        <div class="form-group">
                            <label class="form-label">Enlace RV</label>
                            <span>
                                <input type="text" name="sala_venta_rv" class="form-control">
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Banco</label>
                        <span>
                            <select class="select2 form-control" name="idbancos" required>
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->bancos as $item):?>
                                <option value="<?php echo $item['idbancos'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-dollar-sign"></i>&nbsp;Precio</h2>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label class="form-label">Moneda</label>
                                <span>
                                    <select class="select2 form-control select-moneda" name="moneda">
                                        <option value="" selected="select">Seleccionar...</option>
                                        <option value="S">SOLES</option>
                                        <option value="D">DOLARES</option>
                                    </select>
                                </span>
                            </div>
                            <div class="col-md-4">
                                <label class="form-label">Precio Desde</label>
                                <span>
                                    <input type="number" name="precio_desde" class="form-control">
                                </span>
                            </div>
                            <div class="col-md-4">
                                <label class="form-label">TC Referencial</label>
                                <span>
                                    <input type="number" name="tc_referencial" class="form-control">
                                </span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label class="form-label">Precio Especial</label>
                                <span>
                                    <input type="number" name="precio_especial" class="form-control">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-2" role="tabpanel">
                    <div class="contenedor-dinamico lista-submodulos">
                        <input type="hidden" name="informacion">
                        <div class="encabezado">
                            <div class="row">
                                <div class="col-md-5">
                                    <label class="form-label">Título</label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label">Descripción</label>
                                </div>
                                <div class="col-md-1">
                                </div>
                            </div>
                        </div>
                        <div class="plantilla" style="display: none;">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <span>
                                            <input type="text" class="form-control" data-name="titulo">
                                        </span>
                                    </div>
                                    <div class="col-md-6">
                                        <span>
                                            <input type="text" class="form-control" data-name="descripcion">
                                        </span>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" class="btn btn-danger btn-plantilla" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="contenido"></div>
                        <div class="opcion">
                            <button type="button" class="btn btn-success btn-block" onclick="Fila.agregar(this)"><i class="fas fa-plus"></i> Agregar Información</button>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 980 px de ancho y 460 px de alto</div>
                    <div class="contenido-imagenes">
                        <div data-template='imagenes' style="display: none;">
                            <div class="row-img">
                                <div class="bloque">
                                    <div><strong>Título</strong></div>
                                    <div><input type="text" class="form-control" data-name="titulo" name="titulo[]"></div>
                                </div>
                                <div class="bloque">
                                    <div data-name="imagenes" class="bg_imagen" onclick="Imagenes.seleccionar(this)" data-width="980" data-height="460">
                                        <div class="icon" >
                                            <i class="fas fa-images"></i>
                                            <div>Seleccionar archivo</div>
                                        </div>
                                    </div>
                                    <input type="file" name="imagenes[]" accept="image/*" style="display: none;" onchange="Imagenes.subir(this, event)">
                                </div>
                                <i class="fas fa-times remove" onclick="Imagenes.eliminar(this)"></i>
                            </div>
                        </div>
                        <div data-result="imagenes"></div>
                        <div class="opcion">
                            <button type="button" class="btn btn-success btn-block" onclick="Imagenes.agregar(this)"><i class="fas fa-plus"></i> Agregar Imagen</button>
                        </div>
                    </div>
                </div>
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-4" role="tabpanel">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- <input id="inputSearch" class="controls" name="inputSearch" type="text" placeholder="Fijar coordenadas">
                            <div id="map"></div> -->
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <img src="<?php echo ( $this->hash_ubicacion_mapa != '' ) ? 'productos/imagen/'.$this->hash_ubicacion_mapa.'?t='.time() : 'plantillas/imagenes/google-location.png'; ?>" width="350" class="imagen" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 843 px de ancho y 733 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="843" data-height="733" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_ubicacion_mapa" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-5" role="tabpanel">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <video autoplay muted loop id="videoPreview" width="220">
                                        <source id="videoSource" src="<?php echo ( $this->hash_reel_video != '' ) ? 'productos/video/'.$this->hash_reel_video.'?t='.time() : 'https://dragma3d.com/besco-s.mp4'; ?>" type="video/mp4" />
                                    </video>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Video</button>
                                    <input type="file" onchange="handleFileSelect(event, this);" class="hidden" name="hash_reel_video" accept="video/*" style="display: none;">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
            </div>
        </div>
        <!-- TABS [FIN] -->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Proyecto</button>
    </div>
</form>

<script>

    $("input[name='sala_venta']").click(function(){
        if($(this).is(":checked")){
            $(".contenido-sala-venta").show();
        } else {
            $(".contenido-sala-venta").hide();
        }
    })

    $("input[name='destacado']").click(function(){
        if($(this).is(":checked")){
            $(".contenido-imagen-oferta").show();
        } else {
            $(".contenido-imagen-oferta").hide();
        }
    })

    var Imagenes = {
        dataTemplateImages: $("div[data-template='imagenes']"),
        dataResultImages: $("div[data-result='imagenes']"),
        agregar: function(){
            let divRowimagen = $('<div>').html(this.dataTemplateImages.html());
            //divRowimagen.find("input[type='file']").attr("name")
            this.dataResultImages.append(divRowimagen.html());
        },
        eliminar: function(obj){
            if(confirm("¿Estas seguro de eliminar la imagen?")){
                $(obj).parent().remove();
            }
        },
        seleccionar: function(obj){
            $(obj).parent().parent().find("input[type='file']").click();
        },
        subir: function(obj, event){
            console.log(event);
            var contenedor = $(obj).parent();
            var reader = new FileReader();
            var img = contenedor.find(".bg_imagen");
            var icon = img.find(".icon");
            var img_width = parseInt(img.attr("data-width"));
            var img_height = parseInt(img.attr("data-height"));
            reader.readAsDataURL(event.target.files[0]);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alert('La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.');
                        icon.show();
                        $(obj).val('');
                        img.removeAttr("style");
                        return false;
                    }
                    icon.hide();
                    img.css({"background-image": "url('"+e.target.result+"')"});
                };
            }
        }
    }

    var iconoSeleccionar = '';

    function abrirModalIcono(id){
        iconoSeleccionar = id;
        abrirModal('sistema/seleccionar-icono?id='+id, 'icono');
    }

    $(document).on("click", ".agregar-icono", function(){
        guardarSubmodulos();
    });

    $(document).on("keyup", ".contenedor-dinamico .form-group", function(){
        guardarSubmodulos();
    });

    var Fila = {
        agregar: function(obj){
            let idInputIcono = $.now();
            let contenedor = $(obj).parents(".contenedor-dinamico");
            let plantilla = contenedor.find(".plantilla");
            let plantillaContenido = $("<div>").html(plantilla.html());
            let contenido = contenedor.find(".contenido");
            plantillaContenido.find(".contenedor-icono").attr({
                "data-idicono": idInputIcono,
                "onclick": "abrirModalIcono('"+idInputIcono+"')"
            });
            contenido.append(plantillaContenido.html());
        },
        eliminar: function(obj){
            if(confirm("¿Estas seguro de eliminar la información?")){
                $(obj).parents(".form-group").remove();
                guardarSubmodulos();
            }
        }
    }

    function guardarSubmodulos(){
        let data = [];
        $(".lista-submodulos .contenido .form-group").each(function(){
            let titulo = $(this).find("input[data-name='titulo']").val().trim();
            let descripcion = $(this).find("input[data-name='descripcion']").val().trim();
            if(titulo != ''){
                data.push({
                    titulo: titulo,
                    descripcion: descripcion
                });
                data = data.filter(data => data.titulo != '');
            }
        });
        console.log(data);
        $("input[name='informacion']").val(JSON.stringify(data));
    }

    $(".btn-archivo").click(function(){
        $(this).parent().find("input[type='file']").click();
    });

    var File = {
        upload: function(obj, event){
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let btnDescargar = contenedor.find(".btn-descargar");
            let inputFile = contenedor.find("input[type='file']");
            let validFiles = inputFile.attr("valid-file").split(",");
            if(event.target.files.length){
                if( validFiles.indexOf(event.target.files[0].type) == -1 ){
                    this.message('invalid-format', 'warning');
                    this.restore(obj);
                    return;
                }
                if( event.target.files[0].size > 5000000 ) {
                    this.message('invalid-size', 'warning');
                    this.restore(obj);
                    return;
                }
                btnArchivo.text("Cambiar archivo");
                btnEliminar.show();
            } else {
                this.restore(obj);
            }
        },
        delete: function(obj) {
            this.restore(obj);
        },
        restore: function(obj) {
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let inputFile = contenedor.find("input[type='file']");
            btnArchivo.text("Seleccionar archivo");
            btnEliminar.hide();
            inputFile.val('');
        },
        message: function(type, typeMessage){
            switch(type){
                case 'invalid-format': alerta("El tipo de formato no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
                case 'invalid-size': alerta("El peso máximo no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
            }
        }
    }

    var selectTipoEnlace = $(".select-tipoenlace");
    var contenedorEnlace = $('span[data-contenedor="enlace"]');
    var contenedorPdf = $('span[data-contenedor="pdf"]');

    selectTipoEnlace.change(function(){
        let tipo = $(this).val();
        if( tipo == 'URL' ){
            contenedorEnlace.show();
            contenedorPdf.hide();
            File.restore($(".contenedor-archivo"));
        }else{
            contenedorEnlace.hide();
            contenedorPdf.show();
        }
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                }
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            idempresas: {
                required: true
            },
            nombre: {
                required: true
            },
            tipo_enlace: {
                required: true
            }
        },
        messages: {
            idempresas: {
                required: 'Por favor, seleccionar la empresa'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            tipo_enlace: {
                required: 'Por favor, seleccionar el tipo de enlace'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

    var inputTipoCambioReferencial = $("input[name='tc_referencial']");

    $(".select-moneda").change(function(){
        if( $(this).val() === 'S' )inputTipoCambioReferencial.val('0.00').parent().parent().addClass("disabled");
        else inputTipoCambioReferencial.parent().parent().removeClass("disabled")
    });

    function myMap() {

		var marker = null;
		var inputLatitud = document.getElementById("latitud");
		var inputLongitud = document.getElementById("longitud");
		var inputMap = document.getElementById('map');
		var icon = {
            url: 'https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678111-map-marker-512.png',//place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
		};
		var myLatlng = new google.maps.LatLng(-12.1187024,-77.0353773);
		var map = new google.maps.Map(inputMap, {
			center: myLatlng,
			zoom: 15,
			mapTypeId: 'roadmap'
		});

		marker = new google.maps.Marker({
			map: map,
			draggable: true,
			animation: google.maps.Animation.DROP,
			position: myLatlng,
			icon: icon
		});

		google.maps.event.addListener(marker , 'dragend', function(evt){
			console.log(evt.latLng.lat());
			inputLatitud.value = evt.latLng.lat();
			inputLongitud.value = evt.latLng.lng();
		});

		var input = document.getElementById('inputSearch');

		var options = {
			//types: ['(cities)'],
			componentRestrictions: {country: 'pe'}
		};

		autocomplete = new google.maps.places.Autocomplete(input, options);
		map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

		autocomplete.addListener('place_changed', function() {

			marker.setMap(null);

			var place = autocomplete.getPlace();

			if (place.length == 0 || place.geometry==undefined) {
				inputLatitud.value = 0;
				inputLongitud.value = 0;
				return;
			}else{
				inputLatitud.value = place.geometry.location.lat();
				inputLongitud.value = place.geometry.location.lng();
			}

			if (!place.geometry) {
				window.alert("No hay detalles disponibles para la entrada: '" + place.name + "'");
				return;
			}

			marker = new google.maps.Marker({
				map: map,
				draggable: true,
				animation: google.maps.Animation.DROP,
				position: place.geometry.location,
				icon: icon
			});

			google.maps.event.addListener(marker , 'dragend', function(evt){
				inputLatitud.value = evt.latLng.lat();
				inputLongitud.value = evt.latLng.lng();
			});


			if (place.geometry.viewport) {
				map.fitBounds(place.geometry.viewport);
			} else {
				map.setCenter(place.geometry.location);
				map.setZoom(17);
			}

		});

	}

	$(document).ready(function(){
		myMap();
	});

</script>