<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar PosicionBanner</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/mantenimiento/guardar-agregar-posicionbanner" data-callback="respuesta(response, 'Posicion Banner agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <span>
                <label class="form-label">Página</label>
                <select class="select2 form-control" name="idpaginas">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->paginas as $item):?>
                    <option value="<?php echo $item['idpaginas'];?>"><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control">
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Posicion Banner</button>
    </div>
</form>

<script>

    $(".select2").select2({});

    $("#validar_formulario").validate({
        rules: {
            nombre: {
                required: true
            },
            idpaginas: {
                required: true
            }
        },
        messages: {
            nombre: {
                required: 'Por favor, ingrese el nombre'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>